#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0  ]; then echo "[$0] $@"; fi; }

WEBHOOK_FILE="${WEBHOOK_FILE:-/etc/webhook/hooks.json}";
# WEBHOOK_FILE_URL=${WEBHOOK_FILE_URL:-https://raw.githubusercontent.com/woahbase/alpine-webhook/master/root/defaults/hooks.json}

mkdir -p \
    $(dirname $WEBHOOK_FILE) \
    ;

# fetch hooks json from url if specified
if [ -n "$WEBHOOK_FILE_URL" ];
then
    vecho "Fetching hooks from ${WEBHOOK_FILE_URL}";
    curl \
        --retry 3 \
        --retry-all-errors \
        -o ${WEBHOOK_FILE}.tmp \
        -jSLN "${WEBHOOK_FILE_URL}" \
    && mv ${WEBHOOK_FILE}.tmp ${WEBHOOK_FILE};
fi;

# ensure webhooks json exists
if [ ! -f "${WEBHOOK_FILE}" ];
then
    cp /defaults/hooks.json ${WEBHOOK_FILE};
fi;

# fix permissions
if [ -z "${WEBHOOK_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown ${S6_USER:-alpine}:${PGID:-1000} \
        $(dirname ${WEBHOOK_FILE}) \
        "${WEBHOOK_FILE}" \
        ;
fi;
