#!/usr/bin/with-contenv bash
set -e

WEBHOOK_JSON="${WEBHOOK_JSON:-/etc/webhook/hooks.json}";
# WEBHOOK_JSON_URL=${WEBHOOK_JSON_URL:-https://raw.githubusercontent.com/woahbase/alpine-webhook/master/root/defaults/hooks.json}

mkdir -p \
    $(dirname $WEBHOOK_JSON) \
    ;

# fetch hooks json from url if specified
if [ -n "$WEBHOOK_JSON_URL" ];
then
    echo "Fetching hooks from ${WEBHOOK_JSON_URL}";
    curl \
        --retry 3 \
        --retry-all-errors \
        -o ${WEBHOOK_JSON}.tmp \
        -jSLN "${WEBHOOK_JSON_URL}" \
    && mv ${WEBHOOK_JSON}.tmp ${WEBHOOK_JSON};
fi;

# ensure webhooks json exists
if [ ! -f "${WEBHOOK_JSON}" ];
then
    cp /defaults/hooks.json ${WEBHOOK_JSON};
fi;

chown ${S6_USER:-alpine} \
    ${WEBHOOK_JSON} \
    ;
